apiVersion: v1
kind: Service
metadata:
  name: gpt-neo-service
  namespace: gpt-neo
spec:
  selector:
    app: gpt-neo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
